### ISSUE TITLE
Add "v1.0.1" for V2 Periphery

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-deployments#3]
I will ship the `1.0.1` package later today. @andreivladbrg, could you please add a new `v1.0.1` directory in this repository, which duplicates all the files in `v1.0.0`, but which adds a paragraph at the top of the README that says something along the lines of "The bytecodes for v1.0.1 are the same as those for v1.0.0. We shipped a new version to patch some faulty Foundry remappings."

**Comment by PaulRBerg** [comment]
v1.0.1 deployment made:

https://github.com/sablier-labs/v2-periphery/releases/tag/v1.0.1

**Comment by andreivladbrg** [comment]
Addressed in my latest [commit](https://github.com/sablier-labs/v2-deployments/commit/2b0b0135b0976cbb52ffcb5977cf722fa35da17c).

**Comment by PaulRBerg** [comment]
Changed my mind about this feature.

It doesn't make sense to include a "v1.0.1" deployment given that the bytecodes are exactly the same as those for "v1.0.0".

Shipment != deployments

Additionally, as we've seen with v2-core@1.0.1, only the NFT descriptor changed its bytecode. Thus, the "v1.x" directories in this repo should contain only the contracts that changed their bytecode.

**Comment by PaulRBerg** [comment]
Removed the `v2-periphery/v1.0.1` directory in this commit:

5045bdf6e99557a5b8aa1f8f48fd2bd4d1711751
